export const actions = {
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
  GET_RELATED_PRODUCTS: 'GET_RELATED_PRODUCTS',
  REMOVE_PRODUCT_SELECTED: 'REMOVE_PRODUCT_SELECTED',
  REMOVE_LIST_RELATED: 'REMOVE_LIST_RELATED',
  SET_CATEGORIES: 'SET_CATEGORIES',
  ADD_TO_CART: 'ADD_TO_CART',
  CLEAN_CART: 'CLEAN_CART',
  CLEAN_PRODUCT_SELECTED: 'CLEAN_PRODUCT_SELECTED'
}